# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3001
safe: true


# edit here to achieve your personal greatness
url: http://annebeth.io/
baseurl: /
title: Annebeth Buis
author: Annebeth Buis
description: Personal blog and CV
avatar: profielfoto.jpeg
email: a&#110;&#110;&#101;&#98;&#101;&#116;&#104;&#98;&#117;&#105;&#115;&#64;&#103;&#109;&#97;&#105;&#108;&#46;&#99;&#111;m
github: annebeth
linkedin: annebethbuis
