
title: Annebeth Buis
url: 'annebeth.io'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Annebeth Buis
#tagline: PhD student in Computational Linguistics @ <a href="http://www.colorado.edu/linguistics/">CU Boulder</a>
pic: perfil2.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: anne.buis@colorado.edu
#phone:
website: www.annebeth.io #do not add http://
linkedin: annebethbuis
github: annebeth
#twitter: ''


# Tracker
#analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
